version: "3"
services:
  redis:
    image: redis:alpine
  rowerynka:
    build: ../remote/
    image: stasmade/rowerynka
    depends_on:
      - redis
    env_file:
      - ./rowerynka.env
    ports:
      - 59001:59001
