version: "3"
services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
  rowerynka:
    image: stasmade/rowerynka
    depends_on:
      - redis
    env_file:
      - ./production.env
    ports:
      - 59001:59001
volumes:
  redis_data:
